### ISSUE TITLE
Add link to live demo

### ISSUE THREAD

**Issue by kentcdodds** [MacKentoch/easyFormGenerator#1]
This is truly amazing. I'm very impressed by what you've accomplished with angular-formly!

Have you heard of [rawgit](http://rawgit.com)? I can view your project live using it:
https://rawgit.com/MacKentoch/easyFormGenerator/master/index.html

But even better than that would be to use gh-pages (so you can have a nicer URL). Either way, a link on the repo to a live demo would be nice so people don't have to clone the repo to try it out.

This is awesome.

**Comment by MacKentoch** [comment]
I already plan to create a gh-pages. 

A project website is better you are right.

Just a matter of time but coming soon. 


Thank you for your nice feedback.

**Comment by kentcdodds** [comment]
🎉 👍

**Comment by MacKentoch** [comment]
rawgit link added (as _super easy way to use_ in readme).

Thanks for rawgit, I did not think about it.

Website coming soon.
