### ISSUE TITLE
Label for basic select and group select

### ISSUE THREAD

**Issue by dreamweaver1231** [MacKentoch/easyFormGenerator#18]
Hi,

Label is not visible for basic select and group select compared to other controls like textare, input etc.

Is there a way we can enable them??

**Comment by MacKentoch** [comment]
Hi,

I'd like to make it visible....

But 'till now I don't know why angular formly make label invisible for some custom controls like this `basic select`. 

This basic select is in fact [this nya-bootstrap-select](https://github.com/lordfriend/nya-bootstrap-select) embedded as a formly type [implementation here](http://angular-formly.com/#/example/integrations/nya-bootstrap-select).

**Comment by MacKentoch** [comment]
Omg, I forgot `wrapper: ['bootstrapLabel']` :sweat_smile: 
How did I miss that for so long time?

Ok it means it will be ok, I need to add it :v:

**Comment by MacKentoch** [comment]
Btw, v1.1.0 is the upcoming version.
It makes a long time I'm on it. 

It mainly contents ES6 code update and refactor.

**Comment by dreamweaver1231** [comment]
Thank you so much.

I will definitely checkout the new version

**Comment by MacKentoch** [comment]
It is already in master branch [Easy for generator **step way** version](https://rawgit.com/MacKentoch/easyFormGenerator/master/index_StepWay_ES6.html).

Thank you for remind. I totally forgot this needed fix.

Now I need to fix drag and drop ES6 and EasyFormViewer ES6 then v1.1.0 will be released.
v1.1.0 will be ES5 files deletion for ever (horrible to have both in same project :smile: )
