### ISSUE TITLE
Using EasyFormGenerator as Libarary

### ISSUE THREAD

**Issue by divyakumarjain** [MacKentoch/easyFormGenerator#2]
It would be amazing to see this library as bower or npm component.

**Comment by MacKentoch** [comment]
To be honest I did not plan to make it a library, but... you give some kind **big challenge**.
And... **I love challenge (of this kind^^).**

>That is a really interesting idea! 
I will study it.

Right now, I'm focusing a *website* for it (I develop a custom one).
Then I may add `drag and drop` solution but 
> I want it so basic and easy for anyone who even don't know html!

Thank you for your interest!

**Comment by benoror** [comment]
Just as a reminder from the mailing list, a drag'n'drop example:

https://spengineeringltd-public.sharepoint.com/Pages/FormBuilder.aspx

http://www.spengineeringltd.com/spformlybuilder

**Comment by MacKentoch** [comment]
Nice idea won't be lost in mailbox here. 

Thank you once again!
