### ISSUE TITLE
Typography rules

### ISSUE THREAD

**Issue by mvila** [MacKentoch/easyFormGenerator#21]
Contrary to French, in English there is no space before punctuation marks (colon, semicolon, question mark, etc.).

**Comment by MacKentoch** [comment]
Hi, thank you for pointing out this issue.

I don't see where it comes from...

I need a bit more of your help to understand this.

Would you mind telling me : 
 - which navigator (maybe all of yours?)
 - get your navigator language from console : 
```javascript 
navigator.languages ? navigator.languages[0] : (navigator.language || navigator.userLanguage)
```
- maybe a screen shot? (*if you can't don't worry about it*)

It is strange and I would like to fix it.

**Comment by mvila** [comment]
Sorry, I was speaking about the documentation (the README file).

**Comment by MacKentoch** [comment]
Oh yes :sweat_smile: you are right.

It is clearly a typical french typo, sorry.

Thank you for correcting me. 
I never paid attention to it before (easier to learn grammar than to change habits).

**Comment by MacKentoch** [comment]
It should be ok now.
I hope I did not miss any ponctuation typo.

**Comment by mvila** [comment]
There are still a few <space>+<colon> in the README. Tip: search for " :" (notice the space before the colon) to make sure you get them all.

**Comment by MacKentoch** [comment]
So simple but accurate tip.

Thank you for taking time inspecting typos.
