### ISSUE TITLE
Load as node module with Babel and Browserify

### ISSUE THREAD

**Issue by jarvelov** [MacKentoch/easyFormGenerator#27]
So I've been scratching my head around this for about a day and I can't really get a grip on how to get this to play together with my environment. I might be missing something really simple here but 

However, I'm using Browserify to bundle the dependencies and Babel to import node modules like this:

```import as moduleName from 'module-name';```

The demo versions all load the easyFormGenerator by including it with a script tag like so: ```<script src="public/js/eda.stepway.js></script>```

Is it possible to include easyFormGenerator by requiring it like CommonJS does with ```require('module-name')```?

EDIT: A minimal example of what I'm trying to achieve

```js
//build.js
var fs = require("fs");
var browserify = require("browserify");
var babelify = require("babelify");

browserify({ debug: true })
  .transform(babelify)
  .require("./script.js", { entry: true })
  .bundle()
  .on("error", function (err) { console.log("Error: " + err.message); })
  .pipe(fs.createWriteStream("bundle.js"));
```

```js
//script.js
//Under the hood 'import' is the same as: const angular = require('angular')

import 'angular';
import './node_modules/easy-form-generator/src/app/stepway/edaStepWayEasyFormGen.main.js';
```

```shell
node build.js
Error: 'import' and 'export' may appear only with 'sourceType: module'
```
Am i missing something? Is there another module which can be loaded like this? Babel preset is ```es2015```

**Comment by MacKentoch** [comment]
Hi,

Sorry module is unclear from `npm`.
It was initially only for `bower`but from npm I need to make improvements.

You can't use src, but better use dist bundle since EasyFormGenerator is a vendor module for your project.
 
So import : 
```javascript
import './node_modules/easy-form-generator/dist/js/eda.stepway'
```

**Comment by jarvelov** [comment]
Hi!

Thanks for your response! Using the dist file worked all right, cheers!

**Comment by MacKentoch** [comment]
@jarvelov you are welcome!

I will work on npm package for the next release to make it more simple and standard to import (ES6 or commonJS).
