### ISSUE TITLE
fonts file failed to load

### ISSUE THREAD

**Issue by Aneeskhan** [MacKentoch/easyFormGenerator#3]
console :
![image](https://cloud.githubusercontent.com/assets/10149367/8516321/452a14c8-23cc-11e5-97b2-d6431a67eab6.png)

Network:
![image](https://cloud.githubusercontent.com/assets/10149367/8516327/5875e99e-23cc-11e5-8591-9b9ce92f915d.png)

**Comment by MacKentoch** [comment]
It is related to bootstrap theme css (@import url("//fonts.googleapis.com/css etc ...")).

It occurs on Chrome.

Than js for pointing it, I will bypass this font import soon.

**Comment by MacKentoch** [comment]
I added a **gulp task** to remove `@import url("//fonts.googleapis.com/css`  from `/public/lib/css/bootstrap.min.css`.

You can : 
 - delete yourself this `@import` 
 - `git pull origin master` (if you cloned this repo)
 - download manually 

> so that there will be no more font download error on Chrome.
