### ISSUE TITLE
Loading form and data to edit response

### ISSUE THREAD

**Issue by andrewfam** [MacKentoch/easyFormGenerator#31]
Hi,
Any way to load the form and a submitted response such that the form is used to edit past data?
I tried adding in the data on the demoCtrl.dataModel but the form remains blank?

function demoController($http){
					var demoCtrl = this;
					demoCtrl.fieldsModel		= testACompleteForm();
					demoCtrl.dataModel			= preloadData();
					demoCtrl.submitButtonText = 'Submit this form';
					demoCtrl.cancelButtonText = 'Cancel all';
					
					demoCtrl.submitFormEvent 	= submitFormEvent;

					function submitFormEvent(dataModelSubmitted){
						debugger
						$http({
                    		method:'POST',
                    		url : '{% url "ajax-fresponse-save" %}',
                    		data:  JSON.stringify(dataModelSubmitted),
                    		headers: {'Content-Type': 'application/x-www-form-urlencoded'},
                		}).then(function(){
                    		location.reload();
                		})
					}

					function preloadData(){
						var data = {{ data|safe }}
						return data;
					}

					/**
					 * an easy form generator model as demo
					 * 
					 * here as a demo, it could be retrieved from a database
					 */					
					 function testACompleteForm(){
					 	var data = {{ bf.cfjson|safe }}
						if (data != ""){
							return JSON.parse(data);	
						} else {
							return []
						}
					 }                     

					}

**Comment by MacKentoch** [comment]
In your case you have to deal with async.

I don't see where you load fields and data.
`submitFormEvent ` is a post so you may have a get somewhere?

**Comment by andrewfam** [comment]
Hey, 

Sorry if its not clear.
function preloadData() is used to load the data 
function testACompleteForm()
is used to load the form 

{{ data|safe }} {{ bf.cfjson|safe }}
The above tags are from python/django and used to directly load the data with the page without having to do an async call.

With the above i see the form on page load and can submit the forms but i can't load existing data to edit it.

**Comment by andrewfam** [comment]
![screen shot 2016-10-08 at 10 37 48 pm](https://cloud.githubusercontent.com/assets/1430616/19213862/229f3f86-8da8-11e6-933b-2345d53be0f4.png)
![screen shot 2016-10-08 at 10 38 05 pm](https://cloud.githubusercontent.com/assets/1430616/19213863/22a0da1c-8da8-11e6-9b2d-bfe137566cca.png)

Attached a screenshot of my code and implementation.
The {{ data }} is my python dictionary parsed and the {{ dataModel }} is the scope model used to load user's data. Not too sure why the {{ dataModel }} renders blank when the form loads properly

**Comment by MacKentoch** [comment]
Ok.

So you don't use angular in the regular way: $http or any fetch API to load any piece of model.
*It is not forbidden and works if you know what you do but not advised by angular.*

I used to load data like that in my early days of AngularJS (*when not full SPA with NodeJS or .NET MVC backend*). 
But I used the trick of using `ng-init` (*priority 450*) to be sure angular `ng-controller` (*priority 500 so it loads before ng-init loads = that is good to be sure to pass data from ng-init to controller*) knows about my data.


I don't know Python and in your case Django framework. 
I'm confident your way works. 
But could you test wether controller knows about dataModel and be sure to parse it to JSON (*in preloadData function*) like you did in function `testACompleteForm ` :

```javascript
  function preloadData(){
    var data = {{ data|safe }}
    return JSON.parse(data);
  }
```

**Comment by andrewfam** [comment]
I ran through the easyFormViewer.js file

This on line 155 doesn't seem to be working.
function dataModelWatcher(newDataModel) {
	scope.edaEasyFormViewerDataModel = newDataModel;
}

Checking the scope.edaEasyFormViewerDataModel, it holds my data before being wiped by a blank newDataModel.
Removing the  = newDataModel, the data is loaded but the form still doesn't display the data.
Also the datamodel doesn't update itself anymore.

**Comment by MacKentoch** [comment]
Alright I got it.

It makes a year I did not have an eye in this directive.

I created easyFormViewer to load a form (fields) from a model previously created with easyFormGenerator.

This directive does not load data model but returns data model to parent controller depending user's interaction with the form.

In your case the real fix is not to break the `$watch` over `vm.model`, but would just require to init 

```javascript 
// edaFormViewerDirective
  function linkFct(scope) {
     scope.vm.model  = {}; // here always init empty model into vm.model
    // scope.vm.model = scope.edaEasyFormViewerDataModel // => would init a data model from parent controller
     scope.vm.fields   = loadFieldsModel();
```
