### ISSUE TITLE
Ability to disable form input from demoCtrl.fieldsModel

### ISSUE THREAD

**Issue by puaykaipoh** [MacKentoch/easyFormGenerator#32]
The easyFormGenerator does not allow user to set disable from configuration since 

In function 'addOneColumnControl', function 'addTwoColumnControl', and function 'addThreeColumnControl', var fieldToPush.templateOptions does not have the 'disabled' options.

For example:

![feature expansion](https://cloud.githubusercontent.com/assets/8018090/20306386/e53fd9b2-ab74-11e6-82f5-dcb4797ff3a0.png)

**Comment by MacKentoch** [comment]
Hi

The only way (I see) to use disability in a form generator is when a control needs another one to be valid to be editable.
But such feature doesn't exist yet in easyFormGenerator.

Adding this feature would be great, so any PR are always welcomed.
