### ISSUE TITLE
Show Pre-filled Form

### ISSUE THREAD

**Issue by FahadNoor** [MacKentoch/easyFormGenerator#34]
Is there any way I can pre-fill form built with easyFormViewer?

My use case is that I am taking input from user through easyFormViewer form and saving it in database. Now next time user opens the same form, I want to fill it with values fetched from database.

**Comment by MacKentoch** [comment]
Hi,

See html [form viewer example](https://github.com/MacKentoch/easyFormGenerator/blob/master/preview/formviewer.html#L115). 
*In this example I load a form object `demoCtrl.fieldsModel` after a timeout to simulate a result from server fetch call.*

Do the same with a real fetch with data object: `demoCtrl.dataModel`.
