### ISSUE TITLE
No save/cancel button while editing single field 

### ISSUE THREAD

**Issue by NishadAhsan** [MacKentoch/easyFormGenerator#35]
Hi, thanks a lot for this tool. It's great! 

But I am having some weird issue using the form generator, step way. It shows no button when editing column/input field(inside modal) . So, I cannot add new inputs. Everything else in fine. Tried a lot, could not solve. Help please.

**Comment by MacKentoch** [comment]
Hi,

May I ask you more information?

I'd like to know on which navigator?

I guess since v1.2.0 and now coming soon v2.0.0 it does not occur anymore (I fail to reproduce it).

**Comment by NishadAhsan** [comment]
It was when I was trying to edit column inputs(in the modal). I can't reproduce the same behavior again. After trying for a few times it worked. Maybe I made some small mistake the first few times. Thanks man.
