### ISSUE TITLE
NPM Version 1.2.0

### ISSUE THREAD

**Issue by cristianurbano** [MacKentoch/easyFormGenerator#41]
Hi!

In npm we don't have the 1.2.0 (latest version) of the easy form.

Do you know why?

![npm-easy](https://cloud.githubusercontent.com/assets/2442937/21501642/43983116-cc28-11e6-8ec9-59c9859757e8.png)

Thanks!

**Comment by MacKentoch** [comment]
Hi,

I published again to npm and it seems like it is now ok.

I don't remember what went wrong.
