### ISSUE TITLE
Toaster [$sce:itype] issue

### ISSUE THREAD

**Issue by cristianurbano** [MacKentoch/easyFormGenerator#42]
Hi!

You have the [know toaster issue](https://github.com/jirikavi/AngularJS-Toaster#common-issues) 

`[$sce:itype] Attempted to trust a non-string value in a content requiring a string`

_You have not specified: bodyOutputType: 'trustedHtml' when passing html as a body argument._

----

![toaster](https://cloud.githubusercontent.com/assets/2442937/21507441/04f6972a-cc57-11e6-950c-107ee15ebb67.png)

**Comment by MacKentoch** [comment]
I didn't notice that.

The fix makes sense.
Thank you for pointing out.

**Comment by MacKentoch** [comment]
Working on v2.0.0 *master branch* (next release coming after v1.2.0) it could not reproduce this error.

Maybe it comes from previous versions?

**Comment by MacKentoch** [comment]
Sorry for typo... just not easy on a mobile phone 😅

**Comment by MacKentoch** [comment]
I close it.

if still occurs, re-open it.
