### ISSUE TITLE
Small CSS error

### ISSUE THREAD

**Issue by cristianurbano** [MacKentoch/easyFormGenerator#43]
Hi!

You have a small css error in the [line 303](https://github.com/MacKentoch/easyFormGenerator/blob/master/dist/css/eda.stepway.css#L303) from the sass source

---
![css-error](https://cloud.githubusercontent.com/assets/2442937/21507558/2d1db6f6-cc58-11e6-9818-15de0c5f16cc.png)

**Comment by MacKentoch** [comment]
margin-left and right were commented in sass source 😲 

Ok.
It is now deleted like that no way it wrote strange css.

thanks
