### ISSUE TITLE
Formly Expressions

### ISSUE THREAD

**Issue by timmaybrown** [MacKentoch/easyFormGenerator#5]
Are there any plans to incorporate formly expressions to this generator? This is an amazing project. I'd be happy to see what I could do to add that to it, but didn't know if you already had plans to add this or if I'm missing the goal of the project.

**Comment by MacKentoch** [comment]
Hi thank you for your interests. 

Yes, I already plan to integrate as much formly functionalities (like expressions, new controls etc...) as possible. 

But in a first time, I focus on my current primary objectives : 
 - adding a `drag and drop` way (_already visible in master branch if you are interesting : [here preview](https://rawgit.com/MacKentoch/easyFormGenerator/master/indexDragDrop.html)_)
 - make **easy form generator** easier to integrate to any existing project (factorization, modules...)

After that I will be able to add more extension / complexity in a better structure project (in a maintainability point of view).

In fact it is just a matter of time^^

**Comment by funkytaco** [comment]
>make easy form generator easier to integrate to any existing project (factorization, modules...)

I'm running an Angular-Meteor project and would like to see this. Unfortunately, I'm pro bono consulting so you may not be done in time for my project, but I think this is necessary as I don't see an easy way to integrate this into an existing Angular project.

**Comment by MacKentoch** [comment]
Hi,

**Easy Form Generator** is young and was born just for a personal need in a larger scale personal project (_I did not plan to share it in the beginning_).

> Later I realized how it could be nice to share it.

_Now I improve it every day but it is a lot of work so it takes time._

**If you want to use it there are 2 easy ways (not as optimized as if it were a module to import).**

 - 1st WAY : use **full `index.html`** and associated js/css **as a web page in your project**.
    - **save models to database** when form done (check my article how to save formly models to database :[my article](http://www.erwan-datin.com/tips/how-do-I-store-angular-formly-fields-model-into-database))

 - 2nd WAY : **use easy form generator html section only** as part of YOUR web page. 
   - let models be visible to any controller of your application (use providers or in app.value...), check knees branch that show how to [anees branch - easy form generator embedded](https://github.com/MacKentoch/easyFormGenerator/tree/anees). To sum up the concept :







            
			<section id="pageWfEdit" ng-controller="ngwfWfEditController as vm">

            
         <section id="demoSection" ng-controller="yourController as secondVM">



Now I guess it is not top optimized to integrate right now. 

Be sure I work on it since my aim is to offer a SUPER easy form generator (easy in all meanings).

**Comment by timmaybrown** [comment]
After digging into the source code of your project you may benefit from looking at https://github.com/johnpapa/angular-styleguide for how to modularize your code and clean it up a bit. 

Thank you for sharing your project. I has shown me the possibilities for building a form builder using formly and I'll see what I can come up with.

**Comment by MacKentoch** [comment]
Thanks for your feedback, glad it helps you.


Easy form generator will evolve.

At this stage (far from being a release), it is just a `click index.html and see magic` than an angular module (coded to be shared and more readable).

Don't worry I already know the good way coding angular, that is why I told about making it easier to integrate when I'm done with drag and drop (which was asked to me).

**Comment by timmaybrown** [comment]
Sounds good. I only mentioned the style guide because setting the app into a var like this is bad practice `var ngwfApp = angular.module('ngwfApp' ...etc... `

**Comment by MacKentoch** [comment]
Yes you are right. It is not a best practice but it is not alarmfull if you take a *minimum insurance*.

>It is interesting to highlight why `var myModele = angular.module` is to avoid.

- 1st reason **"most important one"** : collision (imagine another js using a var with same name...)
- 2nd reason  : less performance (may not be noticeable in small project like this one but it is good to know that).

let's have a look in clientMVC.min.js.
You will be able to see my angular modules are in a IIFE :

    ;(function(){
    "use strict";

     //clientMVC.min.js angular modules inside (I named it min since distribution version should be minified see gulp file).

     //all var are isolated here no risk of collision
    }}()


_____

>If you know just 1 guy in all over the world that code perfect in a simple run (no bad practice / all code well commented in a good english), tell us he will be soon hired or will be seen as a liar.

If you want to participate, I would appreciate any kind of help :
 - just fork
 - code
 - then PR

**Comment by MacKentoch** [comment]
## Thanks to yours feedbacks easy form generator is currently evolving

I'm currently adding validation and validation messages (*it is not finished but won't takes years*).

## As an example
Please [check here](https://rawgit.com/MacKentoch/easyFormGenerator/master/index.html) new control `email` with `validation messages` on :
 - `email pattern` validation
 - required field (if set)

## Important 

Developments are not yet finished so
- **please wait few days** —*maybe tomorrow? (don't worry, I will announce it)*— (time I finish adding validation on existing controls)
- **BEFORE updating to lastest version**

## NEW : EASY FORM GENERATOR GITTER

Easy form generator has now a dedicated gitter room : [![Join the chat at https://gitter.im/MacKentoch/easyFormGenerator](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/MacKentoch/easyFormGenerator?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

*Please better use this room to give me all your suggestions that are welcomed and help me to improve easy form generator*
