### ISSUE TITLE
Latest NPM release has git conflict markers

### ISSUE THREAD

**Issue by vinnybod** [MacKentoch/easyFormGenerator#61]
eda.stepway.js has some conflict markers keeping the file from being compiled

209, 211, 213, 687, 689, 691

**Comment by MacKentoch** [comment]
Hi @vinnybod 

I forgot to update non min bundles in v2.1.0 so it should be ok with min bundles.

I've just publish v2.1.1 to fix that (non min bundles updated).

> NOTE: since v2.0.0 you have to import easyFormGenerator css since it has been splited again from JS bunlde so that you can overrides its style depending your needs.

**Comment by vinnybod** [comment]
Thanks! It all compiles now
