### ISSUE TITLE
Error up/down row in basicSelect

### ISSUE THREAD

**Issue by cristianurbano** [MacKentoch/easyFormGenerator#64]
Hi!

We have another issue when trying to down/up options in the basicSelect control.

![error-select](https://cloud.githubusercontent.com/assets/2442937/21824227/28241e0a-d75d-11e6-9dff-b38dfb873c0a.png)
![error-select-2](https://cloud.githubusercontent.com/assets/2442937/21824229/2acbba1e-d75d-11e6-801a-5e392478e442.png)

**Comment by MacKentoch** [comment]
Yes I've just fixed it [ref here](https://github.com/MacKentoch/easyFormGenerator/issues/63#issuecomment-271692706)

Within few hour I push it.
I just hope I find before the other strange bug.

**Comment by vinnybod** [comment]
@cristianurbano does this mean you were able to fix https://github.com/MacKentoch/easyFormGenerator/issues/63#issuecomment-271692706? if so could you please advise?

**Comment by cristianurbano** [comment]
@vinnybod I could not find the problem
