### ISSUE TITLE
Header control template issue

### ISSUE THREAD

**Issue by cristianurbano** [MacKentoch/easyFormGenerator#66]
Hi!

The **Header control** does not have col-xs-12 and formly-field-header classes

![header-issue](https://cloud.githubusercontent.com/assets/2442937/21941813/411f4562-d9a9-11e6-8cee-ad5fe35108f7.png)

Also the radio control has an error in the template:
![radio-issue](https://cloud.githubusercontent.com/assets/2442937/21941895/9fc27206-d9a9-11e6-844a-1dfcf253c94c.png)

**Comment by MacKentoch** [comment]
Hi @cristianurbano 

Sorry I was so busy this week I did not spend a lot of time in easyFormGenerator.

Header and Subtitle don't have any col class like `col-xs-12` but only have `row` class.
*I just need margins left and right (from row class) for them.*

**Does it break something or renders ugly in your application?**

**Comment by cristianurbano** [comment]
Hi @MacKentoch, yes, the header breaks the form when it's not the first element.

The subtitles have the `col-xs-12` and it works as expected.

**Comment by MacKentoch** [comment]
Alright I just though is came from the template.

I will check and fix that.

**Comment by MacKentoch** [comment]
fixed in 2.1.3 (related to header was not a real component and it prevented from angular formly upgrade: now all fixed).

v2.1.3 is coming soon (really soon).

**Comment by MacKentoch** [comment]
soon already happened.

npm is updated get v2.1.3.

**Comment by cristianurbano** [comment]
Thanks @MacKentoch !  I will check it later
