### ISSUE TITLE
I can't view the form to edit

### ISSUE THREAD

**Issue by thiennd212** [MacKentoch/easyFormGenerator#69]
Hi!,

I am beginner to use **easyFormGenerator**  and I have a problem to be your support:
After I saved **FIELDS MODEL (ready to save to database one)** to SQL, I can't view it for edit.
Please view images:
1: Create form
![1](https://cloud.githubusercontent.com/assets/11749837/23090217/363d5966-f5cb-11e6-8351-f3637765aada.PNG)
2: Save to DB
![2](https://cloud.githubusercontent.com/assets/11749837/23090221/409d0802-f5cb-11e6-8762-283fcdd89e18.PNG)
3: View for edit
![3](https://cloud.githubusercontent.com/assets/11749837/23090222/48d64c4a-f5cb-11e6-9ee7-bb2ec1c5bb4e.PNG)

Help me !!!!

**Comment by MacKentoch** [comment]
Hi,

I remember this bug in a previous version.

Cold you give me more details like your dependencies version (most important are angularjs and easy-form-generator).

So that I will check it in the same situation as you.

**Comment by thiennd212** [comment]
Thank u for reply!
It here
![1](https://cloud.githubusercontent.com/assets/11749837/23109753/4bea857a-f74e-11e6-926a-a73e56ed9b15.PNG)
And
![2](https://cloud.githubusercontent.com/assets/11749837/23109754/520120fe-f74e-11e6-95b7-2b4a598ed2a1.PNG)
p/s: I'm new so I had to download the latest version from github into last monday
![3](https://cloud.githubusercontent.com/assets/11749837/23109812/d47d59ee-f74e-11e6-80e4-cd9ffb33c78f.PNG)

**Comment by MacKentoch** [comment]
I don't have this bug until now...

Which node version do you use?
```javascript 
node -v
```

It should be v6.x minimum.

As I can see you added Vietnamese.

It is not included in easyFormGenerator [language files](https://github.com/MacKentoch/easyFormGenerator/tree/master/src/app/stepway/i18n).

So you must have used:
```javascript
npm install
```
then
```javascript
npm run build-prod-stepway
```
by yourself?

**Comment by thiennd212** [comment]
I see different **FIELDS MODEL (ready to save to database one)**  and **testACompleteForm**.
So Why?
