### ISSUE TITLE
Not included in Gulp build

### ISSUE THREAD

**Issue by venkatzifo** [MacKentoch/easyFormGenerator#78]
I have included easy form generator in my bower.json file and installed this module. When i try to build using gulp in my application. I am getting this error

Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:modulerr] Failed to instantiate module eda.easyformGen.dragdropway due to:
ReferenceError: isUndefined is not defined
    at toDebugString (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:96:10)
    at chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:191:16
    at Array.map (<anonymous>)
    at chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:190:46
    at chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:313:17
    at ensure (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:234:38)
    at module (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:311:14)
    at angular.module (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1184:31)
    at angular.module (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1334:38)
    at http://localhost:9000/bower_components/angular/angular.js:4896:22
http://errors.angularjs.org/1.6.4/$injector/modulerr?p0=eda.easyformGen.dragdropway&p1=ReferenceError%3A%20isUndefined%20is%20not%20defined%0A%20%20%20%20at%20toDebugString%20(chrome-extension%3A%2F%2Fighdmehidhipcmcojjgiloacoafjmpfk%2Fdist%2Fhint.js%3A96%3A10)%0A%20%20%20%20at%20chrome-extension%3A%2F%2Fighdmehidhipcmcojjgiloacoafjmpfk%2Fdist%2Fhint.js%3A191%3A16%0A%20%20%20%20at%20Array.map%20(%3Canonymous%3E)%0A%20%20%20%20at%20chrome-extension%3A%2F%2Fighdmehidhipcmcojjgiloacoafjmpfk%2Fdist%2Fhint.js%3A190%3A46%0A%20%20%20%20at%20chrome-extension%3A%2F%2Fighdmehidhipcmcojjgiloacoafjmpfk%2Fdist%2Fhint.js%3A313%3A17%0A%20%20%20%20at%20ensure%20(chrome-extension%3A%2F%2Fighdmehidhipcmcojjgiloacoafjmpfk%2Fdist%2Fhint.js%3A234%3A38)%0A%20%20%20%20at%20module%20(chrome-extension%3A%2F%2Fighdmehidhipcmcojjgiloacoafjmpfk%2Fdist%2Fhint.js%3A311%3A14)%0A%20%20%20%20at%20angular.module%20(chrome-extension%3A%2F%2Fighdmehidhipcmcojjgiloacoafjmpfk%2Fdist%2Fhint.js%3A1184%3A31)%0A%20%20%20%20at%20angular.module%20(chrome-extension%3A%2F%2Fighdmehidhipcmcojjgiloacoafjmpfk%2Fdist%2Fhint.js%3A1334%3A38)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A9000%2Fbower_components%2Fangular%2Fangular.js%3A4896%3A22
    at http://localhost:9000/bower_components/angular/angular.js:66:12
    at http://localhost:9000/bower_components/angular/angular.js:4920:15
    at forEach (http://localhost:9000/bower_components/angular/angular.js:403:20)
    at loadModules (http://localhost:9000/bower_components/angular/angular.js:4880:5)
    at http://localhost:9000/bower_components/angular/angular.js:4898:40
    at forEach (http://localhost:9000/bower_components/angular/angular.js:403:20)
    at loadModules (http://localhost:9000/bower_components/angular/angular.js:4880:5)
    at createInjector (http://localhost:9000/bower_components/angular/angular.js:4802:19)
    at doBootstrap (http://localhost:9000/bower_components/angular/angular.js:1914:20)
    at Object.angular.resumeBootstrap (http://localhost:9000/bower_components/angular/angular.js:1943:12)
http://errors.angularjs.org/1.6.4/$injector/modulerr?p0=app&p1=Error%3A%20%5B%24injector%3Amodulerr%5D%20Failed%20to%20instantiate%20module%20eda.easyformGen.dragdropway%20due%20to%3A%0AReferenceError%3A%20isUndefined%20is%20not%20defined%0A%20%20%20%20at%20toDebugString%20(chrome-extension%3A%2F%2Fighdmehidhipcmcojjgiloacoafjmpfk%2Fdist%2Fhint.js%3A96%3A10)%0A%20%20%20%20at%20chrome-extension%3A%2F%2Fighdmehidhipcmcojjgiloacoafjmpfk%2Fdist%2Fhint.js%3A191%3A16%0A%20%20%20%20at%20Array.map%20(%3Canonymous%3E)%0A%20%20%20%20at%20chrome-extension%3A%2F%2Fighdmehidhipcmcojjgiloacoafjmpfk%2Fdist%2Fhint.js%3A190%3A46%0A%20%20%20%20at%20chrome-extension%3A%2F%2Fighdmehidhipcmcojjgiloacoafjmpfk%2Fdist%2Fhint.js%3A313%3A17%0A%20%20%20%20at%20ensure%20(chrome-extension%3A%2F%2Fighdmehidhipcmcojjgiloacoafjmpfk%2Fdist%2Fhint.js%3A234%3A38)%0A%20%20%20%20at%20module%20(chrome-extension%3A%2F%2Fighdmehidhipcmcojjgiloacoafjmpfk%2Fdist%2Fhint.js%3A311%3A14)%0A%20%20%20%20at%20angular.module%20(chrome-extension%3A%2F%2Fighdmehidhipcmcojjgiloacoafjmpfk%2Fdist%2Fhint.js%3A1184%3A31)%0A%20%20%20%20at%20angular.module%20(chrome-extension%3A%2F%2Fighdmehidhipcmcojjgiloacoafjmpfk%2Fdist%2Fhint.js%3A1334%3A38)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A9000%2Fbower_components%2Fangular%2Fangular.js%3A4896%3A22%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.6.4%2F%24injector%2Fmodulerr%3Fp0%3Deda.easyformGen.dragdropway%26p1%3DReferenceError%253A%2520isUndefined%2520is%2520not%2520defined%250A%2520%2520%2520%2520at%2520toDebugString%2520(chrome-extension%253A%252F%252Fighdmehidhipcmcojjgiloacoafjmpfk%252Fdist%252Fhint.js%253A96%253A10)%250A%2520%2520%2520%2520at%2520chrome-extension%253A%252F%252Fighdmehidhipcmcojjgiloacoafjmpfk%252Fdist%252Fhint.js%253A191%253A16%250A%2520%2520%2520%2520at%2520Array.map%2520(%253Canonymous%253E)%250A%2520%2520%2520%2520at%2520chrome-extension%253A%252F%252Fighdmehidhipcmcojjgiloacoafjmpfk%252Fdist%252Fhint.js%253A190%253A46%250A%2520%2520%2520%2520at%2520chrome-extension%253A%252F%252Fighdmehidhipcmcojjgiloacoafjmpfk%252Fdist%252Fhint.js%253A313%253A17%250A%2520%2520%2520%2520at%2520ensure%2520(chrome-extension%253A%252F%252Fighdmehidhipcmcojjgiloacoafjmpfk%252Fdist%252Fhint.js%253A234%253A38)%250A%2520%2520%2520%2520at%2520module%2520(chrome-extension%253A%252F%252Fighdmehidhipcmcojjgiloacoafjmpfk%252Fdist%252Fhint.js%253A311%253A14)%250A%2520%2520%2520%2520at%2520angular.module%2520(chrome-extension%253A%252F%252Fighdmehidhipcmcojjgiloacoafjmpfk%252Fdist%252Fhint.js%253A1184%253A31)%250A%2520%2520%2520%2520at%2520angular.module%2520(chrome-extension%253A%252F%252Fighdmehidhipcmcojjgiloacoafjmpfk%252Fdist%252Fhint.js%253A1334%253A38)%250A%2520%2520%2520%2520at%2520http%253A%252F%252Flocalhost%253A9000%252Fbower_components%252Fangular%252Fangular.js%253A4896%253A22%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A9000%2Fbower_components%2Fangular%2Fangular.js%3A66%3A12%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A9000%2Fbower_components%2Fangular%2Fangular.js%3A4920%3A15%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%3A9000%2Fbower_components%2Fangular%2Fangular.js%3A403%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%3A9000%2Fbower_components%2Fangular%2Fangular.js%3A4880%3A5)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A9000%2Fbower_components%2Fangular%2Fangular.js%3A4898%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%3A9000%2Fbower_components%2Fangular%2Fangular.js%3A403%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%3A9000%2Fbower_components%2Fangular%2Fangular.js%3A4880%3A5)%0A%20%20%20%20at%20createInjector%20(http%3A%2F%2Flocalhost%3A9000%2Fbower_components%2Fangular%2Fangular.js%3A4802%3A19)%0A%20%20%20%20at%20doBootstrap%20(http%3A%2F%2Flocalhost%3A9000%2Fbower_components%2Fangular%2Fangular.js%3A1914%3A20)%0A%20%20%20%20at%20Object.angular.resumeBootstrap%20(http%3A%2F%2Flocalhost%3A9000%2Fbower_components%2Fangular%2Fangular.js%3A1943%3A12)
    at toDebugString (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:96:10)
    at chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:191:16
    at Array.map (<anonymous>)
    at chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:190:46
    at chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:313:17
    at ensure (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:234:38)
    at module (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:311:14)
    at angular.module (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1184:31)
    at angular.module (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1334:38)
    at http://localhost:9000/bower_components/angular/angular.js:4896:22
http://errors.angularjs.org/1.6.4/$injector/modulerr?p0=eda.easyformGen.dragdropway&p1=ReferenceError%3A%20isUndefined%20is%20not%20defined%0A%20%20%20%20at%20toDebugString%20(chrome-extension%3A%2F%2Fighdmehidhipcmcojjgiloacoafjmpfk%2Fdist%2Fhint.js%3A96%3A10)%0A%20%20%20%20at%20chrome-extension%3A%2F%2Fighdmehidhipcmcojjgiloacoafjmpfk%2Fdist%2Fhint.js%3A191%3A16%0A%20%20%20%20at%20Array.map%20(%3Canonymous%3E)%0A%20%20%20%20at%20chrome-extension%3A%2F%2Fighdmehidhipcmcojjgiloacoafjmpfk%2Fdist%2Fhint.js%3A190%3A46%0A%20%20%20%20at%20chrome-extension%3A%2F%2Fighdmehidhipcmcojjgiloacoafjmpfk%2Fdist%2Fhint.js%3A313%3A17%0A%20%20%20%20at%20ensure%20(chrome-extension%3A%2F%2Fighdmehidhipcmcojjgiloacoafjmpfk%2Fdist%2Fhint.js%3A234%3A38)%0A%20%20%20%20at%20module%20(chrome-extension%3A%2F%2Fighdmehidhipcmcojjgiloacoafjmpfk%2Fdist%2Fhint.js%3A311%3A14)%0A%20%20%20%20at%20angular.module%20(chrome-extension%3A%2F%2Fighdmehidhipcmcojjgiloacoafjmpfk%2Fdist%2Fhint.js%3A1184%3A31)%0A%20%20%20%20at%20angular.module%20(chrome-extension%3A%2F%2Fighdmehidhipcmcojjgiloacoafjmpfk%2Fdist%2Fhint.js%3A1334%3A38)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%3A9000%2Fbower_components%2Fangular%2Fangular.js%3A4896%3A22
    at http://localhost:9000/bower_components/angular/angular.js:66:12
    at http://localhost:9000/bower_components/angular/angular.js:4920:15
    at forEach (http://localhost:9000/bower_components/angular/angular.js:403:20)
    at loadModules (http://localhost:9000/bower_components/angular/angular.js:4880:5)
    at http://localhost:9000/bower_components/angular/angular.js:4898:40
    at forEach (http://localhost:9000/bower_components/angular/angular.js:403:20)
    at loadModules (http://localhost:9000/bower_components/angular/angular.js:4880:5)
    at createInjector (http://localhost:9000/bower_components/angular/angular.js:4802:19)
    at doBootstrap (http://localhost:9000/bower_components/angular/angular.js:1914:20)
    at Object.angular.resumeBootstrap (http://localhost:9000/bower_components/angular/angular.js:1943:12)
http://errors.angularjs.org/1.6.4/$injector/modulerr?

Can anyone help me with this issue ?

### Version
2.3.0

### Directive
- [ ] stepway
- [ ] formViewer
- [x] dragdropway

### Steps to reproduce
1.  
2.  
3.  

### Expected behavior
What should happen

### Actual behavior
What is happening

**Comment by MacKentoch** [comment]
You need to include yourself [the dependencies](https://github.com/MacKentoch/easyFormGenerator/blob/master/README.md#dependencies).

This is wanted so that it avoids collision with existing dependencies on a ln application.

**Comment by venkatzifo** [comment]
@MacKentoch 
I have included the other dependencies needed in my project. Module 'eda.easyformGen.dragdropway' is not getting included in the build. The other dependent modules are getting included. Do I need to change anything in the Bower JSON file ? Not able to include this specific module.  

It would be great if you can help me with this ?

**Comment by MacKentoch** [comment]
Difficult to say without having an eye on your toolchain.

I don't have a Gulp use case example but a Webpack one.
I have a [vendor.js](https://github.com/MacKentoch/easy-form-generator-webpack-example/blob/master/src/vendors.js) file to import my dependencies (*installed  with npm or yarn*) in the application.

Maybe it could give you an insight on the how to and help to fix.

**Comment by venkatzifo** [comment]
Hi, 
We are using the same structure as in the sample application https://github.com/mmizutani/play-gulp-standalone . Can you please integrate this library in that and share with me ?

**Comment by MacKentoch** [comment]
Play gulp alone is a java and not JavaScript boilerplate.

**Comment by venkatzifo** [comment]
Thanks. I have fixed the issue. Modified bower.json file to include in gulp dependencies .
