### ISSUE TITLE
Which licence ?

### ISSUE THREAD

**Issue by jmls** [MacKentoch/easyFormGenerator#8]
Hi - before I start looking at this interesting project, how is it licensed ? I can't find any reference anywhere on the website or github home page

Thanks - from what I've seen on the demos it looks very good .

**Comment by MacKentoch** [comment]
Hi,

Sorry, it was unclear (*only in scripts / packages... files*).

I updated **README file** to make it easy to find.

>I give it for free to anyone and without asking anything in turn.

It is **`MIT license`**, so feel **`FREE`** : 
- to use
- update
- sell 
- anything you want.

And thank you for your feedback, i'm glad it helps.

Keep an eye on the [drag drop version](https://rawgit.com/MacKentoch/easyFormGenerator/master/indexDragDrop.html) that I'm currently developing (not finished).

After that, I will make both version easier to integrate in any angular project (refactoring, modules, templates in templateCache...)

**Comment by MacKentoch** [comment]
README to clearly show MIT license. 
So I close this resolved issue opened for a good idea.

**Comment by jmls** [comment]
Thanks - I didn't want to go around poking in the source code until I knew which licence it was. I am keeping an eye on the drag and drop version - very interesting. Do you have a roadmap / time in mind ? What do you think is missing right now ?

**Comment by MacKentoch** [comment]
I plan to finish `drag and drop way` this month (I had to write a lot of things from scratch so it just took much more time).

Then I take care the `step way` version.
It means refactor, making modules (right now you have to take a lot of html + dependencies to use it on your projects...).

_It won't change the magic behind_ but change 
- maintainability (for me :smile: )
- usability (for anyone using it so it will be :+1:  to use)

_____
Missing features, are features that can added during easy form generator lifetime without impacting existing. It means : 
- new controls 
- new options for customization
- in fact all you see in [angular formly](drag drop version) could be in easy form generator (*it just makes angular formly a kid game to use*).

If one day I had to make a huge patch (I hope not but I take into account this possibility), I would provide a way to migrate old version to new. You know like you, I dislike using something that one day complitely change, so I plan not make such bad experience to anyone (*I'm an easy form generator user too*).
