### ISSUE TITLE
Load existing form from database in drag drop way

### ISSUE THREAD

**Issue by krupak** [MacKentoch/easyFormGenerator#9]
Thanks for creating a nice form generation which has helped me in one of my project. I did like to suggest a way to load existing form created to edit it further. I have passed the configuration object of lines which it takes for rendering but the form is not creating. Can you give a short demo or example of loading the form generated in drag drop version from database to update the form further?

**Comment by MacKentoch** [comment]
Hi @krupak,

You created your form with which form generator `step way`(*directive one* or not) or `drag and drop way`?

In fact, you did well using configuration lines models. So at a first sight it is surprising but interesting.

**Let's resolve your issue :**

To help you, I will ask you to help me first :smile:, don't worry it is easy : 
- [use your model in this `step way` example (replace the one in `testACompleteForm() function`)](https://rawgit.com/MacKentoch/easyFormGenerator/master/dist/index_StepWay_As_Module.html)
- or use it with **`easy form viewer directive`** (*dedicated to load an easy form outside a form generator*) following [this example](https://rawgit.com/MacKentoch/easyFormGenerator/master/dist/index_easyFormViewer_Module.html) 

Then if it does not work, we will have to use another strategy : you will have to give me your model (or another that would not work) so that I will be able to check what is not working.

**Comment by krupak** [comment]
Hi, thanks for your quick response. I have created a form with the drag and drop way. The lines configuration is working using the step way and form viewer directive but its not working for the drag drop way when I am giving the json object to it. As I want to create a new form using the existing form or update the existing form created using the drag and drop way.
Awaiting your response...

**Comment by MacKentoch** [comment]
Thank you @krupak :+1:  for pointing what it seems to be a bug :bug: .

I'll take care of it.

Drag and drop version is still in **beta**, so I recommend to use step way (*module/directive even better*) version.
I guess you prefer drag and drop (I understand I find it so cool).

I was moving step way version to ES6, but I will have a break on step way, and I will focus on drag and drop.

I will make a drag drop simple directive like I did with step way.
It will be an occasion to correct this bug. 

For now, I guess you may be impatient to resolve your issue.

>So if you could provide me a sample model that encounters this bugs I will :hammer:  this :bug: .

**Comment by krupak** [comment]
Hi thanks for taking up this issue. The model I am using is as follows: 

{

                "submitButtonText": "submit",
                "cancelButtonText": "cancel",
                "lines": [
                    {
                        "line": 1,
                        "activeColumn": 1,
                        "columns": [
                            {
                                "numColumn": 1,
                                "exist": true,
                                "control": {
                                    "className": "col-xs-12",
                                    "type": "header",
                                    "key": "",
                                    "templateOptions": {
                                        "label": "",
                                        "required": false,
                                        "description": "Welcome",
                                        "placeholder": "",
                                        "options": [
                            ],
                                        "type": ""
                                    },
                                    "selectedControl": "Header",
                                    "subtype": "",
                                    "cssClass": "col-xs-12",
                                    "edited": true
                                }
                }
            ]
        },
                    {
                        "line": 2,
                        "activeColumn": 1,
                        "columns": [
                            {
                                "numColumn": 1,
                                "exist": true,
                                "control": {
                                    "className": "col-xs-12",
                                    "type": "subTitle",
                                    "key": "",
                                    "templateOptions": {
                                        "label": "",
                                        "required": false,
                                        "description": "Hello",
                                        "placeholder": "",
                                        "options": [
                            ],
                                        "type": ""
                                    },
                                    "selectedControl": "Subtitle",
                                    "subtype": "",
                                    "edited": true
                                }
                }
            ]
        }
    ]

            }

It will be great if you can create a simple drag drop directive to create form with existing lines configuration asap as I have to deliver the project by this weekend. 
Awaiting your response...

**Comment by MacKentoch** [comment]
I'll fix this bug in a first time.

**Comment by krupak** [comment]
Ok thanks, will be awaiting for the solution of it.

**Comment by MacKentoch** [comment]
The reason is drag and drop version lack a method to bind :  
- configuration model (*= easy form form common fields model*) 
- **TO** 
- dragAndDrop model (*=drag and drop particularity : it manages drag and drop UI then update configuration model*).

I'm on it, I'm just busy but it will be ok.

**Comment by MacKentoch** [comment]
Ok, now drag and drop version is able to load fields model : [demo with your model](https://rawgit.com/MacKentoch/easyFormGenerator/master/indexDragDrop.html).

But I have to make it user friendly, it is badly coded in `edaEditController` = just to show you it will be ok :smile:

**Comment by krupak** [comment]
:+1: Thanks for giving the demo with the model. It will help me to complete my project sooner :smile:

**Comment by MacKentoch** [comment]
@krupak you should just wait a bit.

*It will be easier with drag ad drop embedded in a simple directive like that :*

```javascript
<eda-dragdrop-way-easy-form-gen 	
			eda-easy-form-generator-model="demoCtrl.easyFormGeneratorModel"
			eda-save-form-event="demoCtrl.saveForm(edaEasyFormGeneratorModel)">
</eda-dragdrop-way-easy-form-gen>
```

I'm on it, it won't take days.

**Comment by krupak** [comment]
:+1:  OK sure will wait for it.

**Comment by MacKentoch** [comment]
Demo link will soon be updated and won't present your model anymore (as soon as rawgit refresh).

Directive is coming so I cleaned edit controller's code.

**Comment by krupak** [comment]
:+1: sure

**Comment by MacKentoch** [comment]
@krupak here it  : [drag drop directive demo](https://cdn.rawgit.com/MacKentoch/easyFormGenerator/master/dist/index_DragDropWay_As_Module.html).

**How to use :** (*exactly like step way module*)

```javascript
//inject eda.easyformGen.dragdropway in your application
angular
  .module('appDemo', [
    'eda.easyformGen.dragdropway' //injects easy form generator drag and drop way
   ])
```

then directive is so simple : 

```html
<eda-dragdrop-way-easy-form-gen 	
			eda-easy-form-generator-model="demoCtrl.easyFormGeneratorModel"
			eda-save-form-event="demoCtrl.saveForm(edaEasyFormGeneratorModel)">
</eda-dragdrop-way-easy-form-gen>
```

> IMPORTANT : don't forget `drag and drop way` is still in **BETA**. So all may not be functional like in step way. It will be later (not talking about years :smile: )

**Comment by MacKentoch** [comment]
Now I close this issues since drag and drop (still in BETA) is not finished.
Better use step way version (production friendly) and contains more feature.

Now I plan to refactor and migrate to ES6 (*it will help to refactor, and I love ES6*) all easy form generator before going deeper into drag and drop version.

>I hope it will help you, it is now up to you to make cool things :+1:

**Comment by krupak** [comment]
:+1: Thanks, it will help me a lot to complete my project :smile:
